### PR TITLE
Added Alpheios support

### PR DESCRIPTION
**Pull request by elijahjcooke**

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Hey Elijah,
May I ask you why you hardcoded the "grc" parameter ? :) 
Best
Thibault

**Comment by PonteIneptique** [comment]
I think you could either get the information by playing with classes or by upgrading the right XSL here : https://github.com/OpenGreekAndLatin/cts_leipzig_ui/blob/master/cts_leipzig_ui/data/assets/static/xslt/edition.xsl#L25-L71

**Comment by elijahjcooke** [comment]
the activate function requires a lang value, but it doesn't actually use it
though. Let over from an older way the library used to work. Let me make
the change to the library and make a new pull request. it shouldn't affect
things but isn't very clean :)

**Comment by PonteIneptique** [comment]
And note for the tests : try to fix the setup.py which is still using the beta version of packages :')

**Comment by PonteIneptique** [comment]
And update the tests so that they use the right class names for imports ... :')

**Pull request merged**
